# $Id: Makefile.kmk 114390 2026-06-16 14:28:28Z andreas.loeffler@oracle.com $
## @file
# Sub-Makefile for the Shared Clipboard Host Service testcases.
#

#
# Copyright (C) 2011-2026 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

if defined(VBOX_WITH_TESTCASES) && !defined(VBOX_ONLY_ADDITIONS) && !defined(VBOX_ONLY_SDK)

 #
 # Testcase which mocks HGCM to also test the VbglR3-side of Shared Clipboard.
 #
 # Goal is to use and test as much guest side code as possible as a self-contained
 # binary on the host here.
 #
 # Note: No #ifdef TESTCASE hacks or similar allowed, has to run
 #       without #ifdef modifications to the core code!
 #
 tstClipboardMockHGCM_TEMPLATE = VBoxR3TstExe
 tstClipboardMockHGCM_DEFS    = VBOX_WITH_HGCM VBOX_WITH_SHARED_CLIPBOARD VBOX_WITH_SHARED_CLIPBOARD_HOST
 tstClipboardMockHGCM_SOURCES = \
 	tstClipboardMockHGCM.cpp \
 	../VBoxSharedClipboardSvc.cpp \
 	../../testcase/TstHGCMMock.cpp \
 	../../testcase/TstHGCMMockUtils.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
 	$(PATH_ROOT)/src/VBox/Main/src-client/VBoxSharedClipboardSvc-utils.cpp \
 	$(PATH_ROOT)/src/VBox/Additions/common/VBoxGuest/lib/VBoxGuestR3LibClipboard.cpp \
 	$(PATH_ROOT)/src/VBox/HostServices/common/message.cpp
 tstClipboardMockHGCM_LIBS    = $(LIB_RUNTIME)
 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  tstClipboardMockHGCM_INCS += $(PATH_ROOT)/src/VBox/HostServices/SharedClipboard
 endif

 if1of ($(KBUILD_TARGET), linux solaris)
  PROGRAMS += tstClipboardMockHGCM
  tstClipboardMockHGCM_SOURCES += \
  	$(PATH_ROOT)/src/VBox/GuestHost/DisplayServerType.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-x11.cpp \
  	$(PATH_ROOT)/src/VBox/Main/src-client/linux/ClipboardBackendX11.cpp
  tstClipboardMockHGCM_LIBPATH = \
  	$(VBOX_LIBPATH_X11)
  tstClipboardMockHGCM_LIBS   += \
  	Xt \
  	X11
 endif
 if1of ($(KBUILD_TARGET), win)
  PROGRAMS += tstClipboardMockHGCM
  tstClipboardMockHGCM_SOURCES += \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-win.cpp \
  	$(PATH_ROOT)/src/VBox/Main/src-client/win/ClipboardBackendWin.cpp
 endif

 tstClipboardMockHGCM_CLEAN = $(tstClipboardMockHGCM_0_OUTDIR)/tstClipboardMockHGCM.run

 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  tstClipboardMockHGCM_DEFS   += \
  	VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS \
  	$(if $(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS_HTTP),VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS_HTTP,)
  tstClipboardMockHGCM_SOURCES += \
  	../VBoxSharedClipboardSvc-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers-provider-local.cpp
  if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS_HTTP)
   if1of ($(KBUILD_TARGET), linux solaris)
    tstClipboardMockHGCM_SOURCES += \
    	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers-http.cpp
   endif
  endif
  tstClipboardMockHGCM_SOURCES.win += \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardDataObjectImpl-win.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardEnumFormatEtcImpl-win.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardStreamImpl-win.cpp
 endif

 if 0 # Enable this if you want automatic runs after compilation.
  $$(tstClipboardMockHGCM_0_OUTDIR)/tstClipboardMockHGCM.run: $$(tstClipboardMockHGCM_1_STAGE_TARGET)
	export VBOX_LOG_DEST=nofile; $(tstClipboardMockHGCM_1_STAGE_TARGET) quiet
	$(QUIET)$(APPEND) -t "$@" "done"
  OTHERS += $(tstClipboardMockHGCM_0_OUTDIR)/tstClipboardMockHGCM.run
 endif

 #
 #
 #
 PROGRAMS += tstClipboardServiceHost
 tstClipboardServiceHost_TEMPLATE = VBoxR3TstExe
 tstClipboardServiceHost_DEFS     = VBOX_WITH_HGCM UNIT_TEST VBOX_WITH_SHARED_CLIPBOARD_HOST
 tstClipboardServiceHost_SOURCES  = \
 	../VBoxSharedClipboardSvc.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
 	$(PATH_ROOT)/src/VBox/Main/src-client/VBoxSharedClipboardSvc-utils.cpp \
 	$(PATH_ROOT)/src/VBox/HostServices/common/message.cpp \
 	tstClipboardServiceHost.cpp
 tstClipboardServiceHost_INCS += $(PATH_ROOT)/src/VBox/Main/include
 tstClipboardServiceHost_LIBS  = $(LIB_RUNTIME)
 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  tstClipboardServiceHost_INCS += $(PATH_ROOT)/src/VBox/HostServices/SharedClipboard
 endif

 if1of ($(KBUILD_TARGET), linux solaris)
  tstClipboardServiceHost_DEFS += VBOX_WITH_SHARED_CLIPBOARD_X11_LAZY_LOAD
  tstClipboardServiceHost_SOURCES += \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-x11.cpp \
  	$(PATH_ROOT)/src/VBox/Main/src-client/linux/ClipboardBackendX11.cpp
  define def_VBoxTstClipboardServiceHost_libToLazyLoad
   tstClipboardServiceHost_SOURCES += \
   	$$(tstClipboardServiceHost_0_OUTDIR)/$(2)LazyLoad.asm
   tstClipboardServiceHost_CLEAN += \
   	$$(tstClipboardServiceHost_0_OUTDIR)/$(2)LazyLoad.asm
   $$$$(tstClipboardServiceHost_0_OUTDIR)/$(2)LazyLoad.asm: $$(PATH_ROOT)/src/VBox/GuestHost/$(2).def $(VBOX_DEF_2_LAZY_LOAD) | $$$$(dir $$@)
	$$(call MSG_TOOL,VBoxDef2LazyLoad,tstClipboardServiceHost,$$(filter %.def, $$^),$$@)
	$$(QUIET)$$(RM) -f -- "$$@"
	$$(VBOX_DEF_2_LAZY_LOAD) --explicit-load-function --system --library $(2)$$(SUFF_DLL)$$(if $(3),.$(3),) --output "$$@" $$(filter %.def, $$^)
  endef
  if1of ($(KBUILD_TARGET), linux)
   VBOX_TST_CLIPBOARD_SERVICE_HOST_LIBX11_VER = 6
   VBOX_TST_CLIPBOARD_SERVICE_HOST_LIBXT_VER  = 6
   tstClipboardServiceHost_LDFLAGS.linux += $(VBOX_GCC_no-pie)
  endif
  $(evalcall2 def_VBoxTstClipboardServiceHost_libToLazyLoad,$(PATH_ROOT)/src/VBox/GuestHost/libX11.def,libX11,$(VBOX_TST_CLIPBOARD_SERVICE_HOST_LIBX11_VER))
  $(evalcall2 def_VBoxTstClipboardServiceHost_libToLazyLoad,$(PATH_ROOT)/src/VBox/GuestHost/libXt.def,libXt,$(VBOX_TST_CLIPBOARD_SERVICE_HOST_LIBXT_VER))
 endif

 tstClipboardServiceHost_CLEAN   += $(tstClipboardServiceHost_0_OUTDIR)/tstClipboardServiceHost.run

 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  tstClipboardServiceHost_DEFS    += VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS
  tstClipboardServiceHost_SOURCES += \
  	../VBoxSharedClipboardSvc-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers-provider-local.cpp
 endif

 #
 #
 #
 PROGRAMS += tstClipboardServiceImpl
 tstClipboardServiceImpl_TEMPLATE = VBoxR3TstExe
 tstClipboardServiceImpl_DEFS     = VBOX_WITH_HGCM UNIT_TEST VBOX_WITH_SHARED_CLIPBOARD_HOST
 tstClipboardServiceImpl_SOURCES  = \
 	../VBoxSharedClipboardSvc.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
 	$(PATH_ROOT)/src/VBox/HostServices/common/message.cpp \
 	tstClipboardServiceImpl.cpp
 tstClipboardServiceImpl_SOURCES.win = \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-win.cpp
 tstClipboardServiceImpl_LIBS     = $(LIB_RUNTIME)
 tstClipboardServiceImpl_CLEAN    = $(tstClipboardServiceImpl_0_OUTDIR)/tstClipboardServiceImpl.run

 if defined(VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS)
  #
  # File transfer tests.
  #
  PROGRAMS += tstClipboardTransfers
  tstClipboardTransfers_TEMPLATE = VBoxR3TstExe
  tstClipboardTransfers_DEFS     = VBOX_WITH_HGCM UNIT_TEST VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS
  tstClipboardTransfers_SOURCES  = \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers-provider-local.cpp \
  	tstClipboardTransfers.cpp

  #
  # Windows IDataObject tests.
  #
  PROGRAMS.win += tstClipboardDataObjectWin
  tstClipboardDataObjectWin_TEMPLATE = VBoxR3TstExe
  tstClipboardDataObjectWin_DEFS    += UNICODE VBOX_WITH_HGCM UNIT_TEST VBOX_WITH_SHARED_CLIPBOARD VBOX_WITH_SHARED_CLIPBOARD_TRANSFERS
  tstClipboardDataObjectWin_SOURCES  = \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-helper.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-win.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-transfers-provider-local.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardDataObjectImpl-win.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardEnumFormatEtcImpl-win.cpp \
  	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/ClipboardStreamImpl-win.cpp \
  	tstClipboardDataObjectWin.cpp
  tstClipboardDataObjectWin_LIBS     = $(LIB_RUNTIME)
 endif
endif

#
# List of above testcases that will be included in the ValKit.
#
ifdef VBOX_WITH_VALIDATIONKIT_UNITTESTS_PACKING
 if1of ($(KBUILD_TARGET), linux solaris win)
  VALKIT_UNITTESTS_WHITELIST_GUEST_ADDITIONS += \
  	tstClipboardMockHGCM
 endif
endif # VBOX_WITH_VALIDATIONKIT_UNITTESTS_PACKING

include $(FILE_KBUILD_SUB_FOOTER)
