' $Id: clipboard_sequence.iuml 114405 2026-06-17 13:18:09Z andreas.loeffler@oracle.com $
'' @file
' UML definition for PlantUML - VirtualBox Clipboard Sequence - Draft
'

'
' Copyright (C) 2025-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title VirtualBox Clipboard API Sequence - 7.x Draft
hide empty description

actor "User (Host)" as U
participant Host as H
participant "VBoSVC" as VBoxSVC
participant "VBoxC" as VBoxC
participant "Client" as Client
participant VBoxService as VBoxService
participant Guest as G

== Host > Guest (Data) ==

U -> H: Copy data (e.g., Ctrl+C)
loop
  H -> VBoxSVC: <watches host clipboard>
end
VBoxSVC -> VBoxC: issues IClipboardFormatChangedEvent
VBoxC -> Client: issues IClipboardFormatChangedEvent
Client -> VBoxC : IClipboard::createFormat(mimeType)
Client -> VBoxC : IClipboard::writeFormats(formats)
VBoxC -> VBoxService  : queue VBOX_SHCL_HOST_MSG_FORMATS_REPORT
G -> VBoxService : VBOX_SHCL_GUEST_FN_MSG_PEEK_WAIT / MSG_GET
VBoxService -> G  : VBOX_SHCL_HOST_MSG_FORMATS_REPORT(formats)
G -> G : reports formats to guest clipboard
U -> G: Paste data (e.g., Ctrl+V)
G -> VBoxService  : VBOX_SHCL_GUEST_FN_DATA_READ(format)
VBoxService -> VBoxC  : request cached host data for guest
VBoxC -> Client : issues IClipboardDataChangedEvent after data is read
Client -> VBoxC : IClipboard::createFormat(mimeType)
Client -> VBoxC : IClipboard::createItem(Host, format, buffer)
Client -> VBoxC : IClipboard::writeData(Copy, item)
VBoxC -> VBoxService  : provide data for VBOX_SHCL_GUEST_FN_DATA_READ
VBoxService -> G  : VBOX_SHCL_GUEST_FN_DATA_READ returns data

== Guest > Host (Data) ==

U -> G: Copy data (e.g., Ctrl+C)
loop
  Guest -> VBoxService : <watches guest clipboard>
end
G -> VBoxService : VBOX_SHCL_GUEST_FN_REPORT_FORMATS(formats)
VBoxService -> VBoxC : report guest formats
VBoxC -> Client: issues IClipboardFormatChangedEvent
Client -> VBoxC : IClipboard::readFormats()
Client -> VBoxC : IClipboard::readData(Copy)
VBoxC -> VBoxService : queue VBOX_SHCL_HOST_MSG_READ_DATA[_CID](format)
G -> VBoxService : VBOX_SHCL_GUEST_FN_MSG_PEEK_WAIT / MSG_GET
VBoxService -> G : VBOX_SHCL_HOST_MSG_READ_DATA[_CID](format)
G -> VBoxService : VBOX_SHCL_GUEST_FN_DATA_WRITE(format, data)
VBoxService -> VBoxC : report guest data
VBoxC -> Client : issues IClipboardDataChangedEvent
Client -> VBoxC : IClipboard::writeData(Copy, item)
VBoxC -> VBoxSVC : writes to host clipboard

== Host > Guest (Files) ==

' TBD

== Guest > Host (Files) ==

' TBD

@enduml
' EOF
