' $Id:
'' @file
' UML definition for PlantUML - Guest Control directory enumeration sequence diagram.
'

'
' Copyright (C) 2013-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title Enumerating a guest directory
!include include/guestctrl_header.iuml
!include include/guestctrl_sessioncreate.iuml
API -> IGuestSession : DirectoryOpen
create IGuestDirectory
IGuestSession -> IGuestDirectory : << Creates >>
activate IGuestDirectory
create IGuestProcess
IGuestDirectory -> IGuestProcess : << Creates >>
activate IGuestProcess
IGuestProcess -> IGuestSession : << Creates IGuestProcess >>
IGuestDirectory -> API : returns IGuestDirectory
API -> IGuestDirectory : Read
activate IGuestProcess
loop Process is not completed
    IGuestDirectory -> IGuestProcess : WaitFor(Exit)
    IGuestDirectory -> IGuestProcess : WaitFor(StdOut | StdErr, timeout)
    opt Data from StdOut
        IGuestDirectory -> IGuestProcess : Read(data)
        IGuestDirectory -> IGuestDirectory : << Parses data >>
        opt Current data block complete
            create IGuestFsObjInfo
            IGuestDirectory -> IGuestFsObjInfo : << Creates >>
            activate IGuestFsObjInfo
            IGuestDirectory -> IGuestFsObjInfo : SetData(data)
            IGuestFsObjInfo -> API : returns IGuestFsObjInfo
        end
    else
    end
end
deactivate IGuestFsObjInfo
API -> IGuestFsObjInfo : << Releases >>
deactivate IGuestFsObjInfo
destroy IGuestFsObjInfo
API -> IGuestDirectory : << Releases >>
IGuestDirectory -> IGuestProcess : Kill
destroy IGuestProcess
destroy IGuestDirectory
!include include/guestctrl_sessiondestroy.iuml
!include include/guestctrl_footer.iuml
@enduml
