' $Id: guestctrl_ex_process.iuml 114403 2026-06-17 13:10:57Z andreas.loeffler@oracle.com $
'' @file
' UML definition for PlantUML - Guest Control process handling sequence diagram.
'

'
' Copyright (C) 2013-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title Creating and handling a guest process
!include include/guestctrl_header.iuml
!include include/guestctrl_sessioncreate.iuml
!include include/guestctrl_processcreate.iuml
== Using the guest process ==
activate API
loop Process is not completed
    API -> IGuestProcess : WaitFor(Exit)
    opt Writing to process
        API -> IGuestProcess : WaitFor(StdIn, timeout)
        API -> IGuestProcess : Write(data)
    else Reading from StdOut/StdErr
        API -> IGuestProcess : WaitFor(StdOut | StdErr, timeout)
        API -> IGuestProcess : Read(data)
    end
end
deactivate API
!include include/guestctrl_processdestroy.iuml
!include include/guestctrl_sessiondestroy.iuml
!include include/guestctrl_footer.iuml
@enduml
